### PR TITLE
Add email auth

### PR DESCRIPTION
**Pull request by ching56**
It seems that email verification and KYC are different parts ( email not part of KYC) in document, but those processes are similar.
Do I need to rename current KYC to SNS and merge them to a KYC group?

### CODE REVIEW

**Comment by chihsuan** [comment]
@ching56: Yes, you're right. They are in different parts so you don't need to merge them as a group. 
I've quickly reviewed the PR. Overall, looks good. But please, in the next step, think about if it's possible to refactor the KYC and the email. Since there have many duplicates parts, we should abstract similar parts to shared components or utils for reuse. Thanks!

**Comment by TseHang** [comment]
I agree to @chihsuan 's comment.
We should abstract similar parts to shared components or utils for reuse.
Thanks 😄

**Comment by ching56** [comment]
I abstract 3 components: VerifyForm, ValidateInput and Section.

I would like to confirm that : 
In VerifyForm and ValidateInput, I use state provided by react instead of redux, since I think those state are only related to their parent.

Please review, thanks!

**Comment by TseHang** [comment]
It looks good now.
However, `KYCScreen` and `EmailScreen` are still look-alike, and so do `KYCVerifyScreen` and `EmailVerifyScreen`. Maybe we can inject different props in containers, then connect component when you need.


like
```javascript
const mapStateToProps = (state: any) => ({
  loading: state.auth.isLoading,
});
const mapDispatchToProps = {
  reqToken: reqKYCToken,
};

export default connect(mapStateToProps, mapDispatchToProps)(ReqAuthTokenScreen);
```

**Comment by ching56** [comment]
Issues mentioned above might be solved, please review again 🙏  , thanks!

**Comment by chihsuan** [comment]
I think this is okay now. Let me merge this first, then we can start to test them. If any issues are found, just create a issue either on here or asana, fix it and open a new PR.

**Pull request merged**
